version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: color-eyre
    versions:
    - "> 0.5.1, < 0.6"
  - dependency-name: hyper
    versions:
    - 0.14.6
  - dependency-name: libc
    versions:
    - 0.2.84
    - 0.2.85
    - 0.2.87
    - 0.2.88
    - 0.2.89
    - 0.2.90
    - 0.2.91
    - 0.2.92
  - dependency-name: tokio
    versions:
    - 1.1.0
    - 1.1.1
    - 1.3.0
  - dependency-name: serde
    versions:
    - 1.0.124
  - dependency-name: once_cell
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
  - dependency-name: serde_json
    versions:
    - 1.0.63
  - dependency-name: futures
    versions:
    - 0.3.13
