language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

os:
  - linux
  - osx


matrix:
  allow_failures:
    - rust: nightly
  exclude:
  - os: osx
    rust: beta
  - os: osx
    rust: nightly

before_script:
  - rustup component add clippy
  - rustup component add rustfmt

script:
  - cargo clippy
  - cargo fmt -- --check
  - cargo test
  - cargo build --release
