language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
os:
  - linux
  - osx

matrix:
  allow_failures:
  - rust: nightly
  exclude:
  - os: osx
    rust: beta
  - os: osx
    rust: nightly

before_script: |
  if [[ $TRAVIS_RUST_VERSION != "nightly" ]]; then
    rustup component add clippy
    rustup component add rustfmt
  fi

script: |
  if [[ $TRAVIS_RUST_VERSION != "nightly" ]]; then
    cargo clippy
    cargo fmt -- --check
  fi

  cargo test

before_deploy:
  - 'cargo build --release'
  - |
    mkdir bin
    cp -f target/release/oxidux "bin/oxidux-$TRAVIS_TAG-$TRAVIS_OS_NAME"

deploy:
  provider: releases
  api_key:
    secure: iuHZgX4U31ihFm09WPshPpw8srI5pW7E1Ec9SR4jVBg0TFEWkR6rrrD6HrQMOtmeWyX29rIpl402uYSaSOdCTfHzmiXkZCG9HZIWDe1wHo/Oh/bngrGQSsPWw9s7AfR/j/vM69jb5y5qFZyltzTPdvf8uWiXfT4bJpLdXY/4wNmGCgfpy7F8gavkwQbcrb5SMVOUQNGcOekFwpcDHG4q4jFMQsC+9VAScDJ0t6j1weTldnwxyFEDniFg6erz+H3Yb/RjCovAf63nfmdHMO1ZRLG1TGyIIoe/4iqGxGaWfsoEY6oVZ5BmW0bm01VCXrRzkXwtjAY0WK6c2ybVbZ3w0I1xf0FrcNHBIveNcAlwAuXtnpjm2OAUvhTyVqBor6VDPHZMLGAjg0PGEHJTfpWz1rl28IpgTDEIXVjc2z5I2h9pg6PBMULVXSOprwz/eJnTaldnRsIjkkzeiSW53ieZ+PJWyuZVC25QLMjdZIlgczFmffKtclV7XfMfqMsKWg9P+WPBUMEmoLCnqPPtRGo/J6BEkEQdB6m8gy0PAUogDOyS8qJFjDq8fE5LREkjwySK4IfS3fEEUfaFORwwLwZzeOTw5Eh3GnYLgslpd6Og2sILxOWeNP23s5CV/0PPBWrAM4AoqSNXqQxRRM1nH2GR4TyO3RXRCkLGeQUzYse27wE=
  file: 'bin/**'
  skip_cleanup: true
  on:
    repo: jonmast/oxidux
    # tags: true
    condition: '$TRAVIS_RUST_VERSION == "stable"'
