[general]
proxy_port = 1234

[[apps]]
directory = "~"
name = "bar"
port = 9000
command = "echo hello there"

[[apps]]
directory = "~"
name = "foo"
port = 80
command = "sleep 10 && echo $USER && echo $PORT"

[[apps]]
directory = "~/dev/kingandpartners/vanilla-client"
name = "vanilla"
port = 9124
command = "bin/rails s -p $PORT"
