version: 2.0
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile

      - restore_cache:
          keys:
            - cargo-dependencies-{{ checksum "Cargo.lock" }}
            - cargo-dependencies

      - run:
          name: Check code style
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: Check code format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Run tests
          command: |
            cargo test
      - run:
          name: Compile binary
          command: |
            cargo build --release

      - store_artifacts:
          prefix: target/release
          path: oxidux

      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
          key: cargo-dependencies-{{ checksum "Cargo.lock" }}
