version: 2.0
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
        name: Check code formatting
        command: |
          cargo clippy
      - run:
        name: Run tests
        command: |
          cargo test
