version: 2.0
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Check code style
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: Check code format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Run tests
          command: |
            cargo test
