version: 2.0
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Check code formatting
          command: |
            rustup component add clippy
            cargo clippy
      - run:
          name: Run tests
          command: |
            cargo test
